version: "3"

services:
  api:
    build: ./src/api
    depends_on:
      - database
    environment:
      DATABASE_HOST: database # ${DATABASE_HOST}
      DATABASE_PASSWORD: password # ${DATABASE_PASSWORD}
      DATABASE_PORT: 5432 #${DATABASE_PORT}
      DATABASE_USER: user # ${DATABASE_USER}
    volumes:
      - ./src/api:/app
    ports:
      - 8080:8080

  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password # ${DATABASE_PASSWORD}
      POSTGRES_USER: user # ${DATABASE_USER}

  database-admin:
    image: dpage/pgadmin4
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: email@html.erb # ${DATABASE_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: password # ${DATABASE_ADMIN_PASSWORD}
    ports:
      - 5555:80
