version: "3"

services:
  api:
    build: ./src/api
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
    volumes:
      - ./src/api:/app
    ports:
      - 8080:8080
